services:
  devops3:
    image: localhost:8082/devops3
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      AMBIENTE: develop
      API_KEY: /run/secrets/api-key
#     secrets:
#       - api-key
# secrets:
#   api-key:
#     file: api-key.txt