pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
            stages {
                stage('checkout') {
                    steps {
                        checkout scm
                    }
                }
                stage('Instalar dependencias node') {
                    steps {
                        sh 'npm install'
                    }
                }
                stage('Ejecutar pruebas unitarias') {
                    steps {
                        sh 'npm run test'
                    }
                }
                stage('Compilar proyecto') {
                    steps {
                        sh 'npm run build'
                    }
                }
            }
        }
        stage('Crear imagen docker') {
            steps {
                script {
                    docker.withRegistry('http://localhost:8082', 'nexus-key') {
                        sh 'docker build -t localhost:8082/mi-proyecto-devops .'
                        sh "docker tag localhost:8082/mi-proyecto-devops localhost:8082/mi-proyecto-devops:${env.BUILD_NUMBER}"
                        sh 'docker push localhost:8082/mi-proyecto-devops'
                        sh "docker push localhost:8082/mi-proyecto-devops:${env.BUILD_NUMBER}"
                    }
                }
            }
        }
    }
}
